### ISSUE TITLE
UID settings seem to be invalid.

### ISSUE THREAD

**Issue by daiaji** [ServerContainers/samba#48] opened 2021-10-08 04:31 UTC
I use samba in podman.
`podman run -d --name samba -e ACCOUNT_test=test -e UID_test=0 -e "SAMBA_VOLUME_CONFIG_public=[Public]; path=/shares/public; valid users = test; guest ok = no; read only = no; browseable = yes" -v %h/ZFS/test:/shares/public -p 4450:445 -p 1390:139 -p 4450:445/udp -p 1390:139/udp servercontainers/samba`
But when I upload files to the smb folder, the fault prompts lack of permissions.
。
```
################################################################################

Welcome to the servercontainers/samba

################################################################################

>> CONTAINER: starting initialisation
>> SAMBA CONFIG: no $SAMBA_CONF_LOG_LEVEL set, using '1'
>> SAMBA CONFIG: no $SAMBA_CONF_WORKGROUP set, using 'WORKGROUP'
>> SAMBA CONFIG: no $SAMBA_CONF_SERVER_STRING set, using 'Samba Server'
>> SAMBA CONFIG: no $SAMBA_CONF_MAP_TO_GUEST set, using 'Bad User'
>> ACCOUNT: adding account: test
startsmbfilepwent_internal: file /var/lib/samba/private/smbpasswd did not exist. File successfully created.
Added user test.
Changing password for test
New password: 
Bad password: too weak
Retype password: 

passwd: password for test changed by root
New SMB password:
Retype new SMB password:

Enabled user test.
>> ZEROCONF: samba.service file
############################### START ####################################
<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
 <name replace-wildcards="yes">%h</name>
 <service>
   <type>_smb._tcp</type>
   <port>445</port>
 </service>
</service-group>
################################ END #####################################
>> CMD: exec docker CMD
runsvdir -P /container/config/runit
Found user 'avahi' (UID 86) and group 'avahi' (GID 86).
Successfully dropped root privileges.
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Successfully called chroot().
Successfully dropped remaining capabilities.
Loading service file /services/samba.service.
Joining mDNS multicast group on interface lo.IPv6 with address ::1.
New relevant interface lo.IPv6 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
cannot read additional dns hostnames from testparm
cannot read netbios aliases from testparm
starting.
open_ep: SO_RCVBUFFORCE: Operation not permitted
Server startup complete. Host name is ca079d12b56a.local. Local service cookie is 2376014848.
Service "ca079d12b56a" (/services/samba.service) successfully established.
open_ep: SO_RCVBUFFORCE: Operation not permitted
smbd version 4.14.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2021
uid=0 gid=0 euid=0 egid=0
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[Public]"
added interface tap0 ip=10.0.2.100 bcast=10.0.2.255 netmask=255.255.255.0
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
Failed to fetch record!
waiting for connections
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
check_ntlm_password:  authentication for user [test] -> [test] -> [test] succeeded
Processing section "[Public]"
test-systemproductname (ipv4:10.0.2.100:38292) connect to service Public initially as user test (uid=1000, gid=1000) (pid 85)
```
But I obviously set the UID to 0.

**Comment by MarvAmBass** [comment] 2021-10-08 04:45
Hi there, I'd say the problem is by creating a user and giving him the already taken userid of `root` - use a userid from the user range.

So there seems to be a permission problem. just try the following: create a new folder for this test, configure a user with a userid from the user range using the `ACCOUNT_test` and `UID_test`.

you can set permissions to this folder from inside podman (don't know if it also has a `exec -ti` like feature) if the folder is owned by your testuser it should work. or you edit the permissions from outside your container.

**Comment by daiaji** [comment] 2021-10-08 05:02
I tried `chown 1000 /shares/public`. After doing so, it seems that it can be uploaded normally, but in fact the original owner of the `/shares/public` file is root. This may be the reason why it cannot be written. I am not the permission management of docker.  Especially clear.

**Comment by MarvAmBass** [comment] 2021-10-08 06:01
thats a good point, I remember that some container runtimes might use randomized uuids for running inside the container, maybe that's the case with podman.

ahhh so you use the rootless mode? isn't this the mode with the randomized uids?

from the docker world if you mount a volume from outside the permissions will not automatically change with the mount - so if you want to write from within the docker container to the volume you need to make sure to have the appropriate access rights

**Comment by daiaji** [comment] 2021-10-08 06:26
Podman rootless mode basically maps the root user in the container to the running user running Podman, but using other users in the container will be mapped to a UID greater than 10000.

**Comment by MarvAmBass** [comment] 2021-10-08 06:31
can you check if it works without this rootless mode?

**Comment by daiaji** [comment] 2021-10-08 06:33
I've changed the Samba user to root, and it seems to be working.

**Comment by MarvAmBass** [comment] 2021-10-08 06:36
I'll close this issue then

**Closed as completed by MarvAmBass** 2021-10-08 06:36 UTC
